### ISSUE TITLE
Installation unclear

### ISSUE THREAD

**Issue by jhh931** [shumatech/BOSSA#128]
The project contains an 'install' directory, but I fail to see/read  how I should install BOSSA.
A few word on this (in readme?)  would be helpful for the user.

**Comment by beikeland** [comment]
Makefile seems to use the contents to generate packages for windows, mac and linux; but you might want to just download the binaries? https://github.com/shumatech/BOSSA/releases

**Comment by jhh931** [comment]
That should do it, thanks for the pointer
