### ISSUE TITLE
wrong GPNVM Bit handling

### ISSUE THREAD

**Issue by iddq** [shumatech/BOSSA#17]
see 7.2.3.10 GPNVM Bits in the datasheet

http://www.atmel.com/Images/Atmel-11057-32-bit-Cortex-M3-Microcontroller-SAM3X-SAM3A_Datasheet.pdf

bit2 is flash selection and not bor!

```
void
EefcFlash::setBor(bool enable)
{
    if (!_canBrownout)
        return;

    waitFSR();
    writeFCR0(enable ? EEFC_FCMD_SGPB : EEFC_FCMD_CGPB, 2);
}
```

**Comment by shumatech** [comment]
The SAM3X/A are not officially supported devices as I do not have a board with them on it to do regression testing on.

**Comment by iddq** [comment]
you can check the datasheet bit2 is flash selection and not bor!
