### ISSUE TITLE
Which is the canonical version?

### ISSUE THREAD

**Issue by projectgus** [shumatech/BOSSA#2]
Hi,

Could you please let me know which BOSSA repository out there is the canonical one?

I found the original one via the website which points to 
http://sourceforge.net/p/b-o-s-s-a/code/ref/master~/

And that repo has some commits from April 2012 that don't appear in this github version. However the version on github has newer commits from September, although those just change the license to BSD.

(To make matters more confusing, I've just forked this repository on github but am about to push commits that came from the sourceforge repo. But that's my fault for being difficult I think. ;).)

Thanks so much for bossa, btw. Adding ATSAM4L support to bossac is infinitely more preferable than having to use Windows for every upload, which is the only other option as Atmel haven't updated the Linux version of SAM-BA for some time!

Cheers,

Angus

**Comment by cmaglie** [comment]
@projectgus 
so much time no answers...

IIRC, with @shumatech support, the development has been moved from sourceforge to github, here in this repository. Maybe at some @shumatech needed to hot-fix something and used the other repository in a hurry?

Anyway, let's try to converge all the forks together, see #27.
