### ISSUE TITLE
Fast-forward master branch into arduino branch

### ISSUE THREAD

**Issue by cmaglie** [shumatech/BOSSA#27]
Hi @shumatech 

I'm wondering if it still makes sense to have two different branches, one from the original bossac (`master` branch) and the other the arduino version (`arduino` branch)?

From the git log I see that the `master` branch could be fast-forwarded to the current `arduino` branch, would you mind if I do that, and let everyone continue to work on the master branch?

**Comment by projectgus** [comment]
(Following on from #2). Wow, blast from the past! If there is a current version then I have ATSAM4L support here, from back in 2013: https://github.com/shumatech/BOSSA/compare/master...projectgus:atsam4l

... that I'd be happy to send a PR for.

**Comment by shumatech** [comment]
Hi @cmaglie 

I'm fine with merging the arduino branch into master so long as there are no Arduino-specific functionality as a default.  All board-specific functions should be enabled by command line switches.  I haven't used any Atmel (or is it Microchip now?) processors in designs for several years now so I'm not in a good position to test any BOSSA changes.  If someone is willing to take this up and upgrade the GUI for the latest changes then that would be great.

**Comment by cmaglie** [comment]
Wonderful, thanks @shumatech !
