### ISSUE TITLE
Flashing to SAM4S2 sometimes fails if the firmware is over 16kB

### ISSUE THREAD

**Issue by Grix** [shumatech/BOSSA#29]
I am making a firmware flashing tool using bossac but I encountered a problem. Sometimes, but not always, the flashing fails if the firmware exceeds 16kB. It then looks like this:

```
Device found on COM4
Atmel SMART device 0x289b07e0 found

Write 16588 bytes to flash (33 pages)
[==============================] 100% (33/33 pages)
done in 0.500 seconds

Verify 16588 bytes of flash
[==============================] 100% (33/33 pages)
Verify failed
Page errors: 1
Byte errors: 204
```

However if I try any other file below 16kB, it works fine. The SAM4S2 has way more than 16kB program flash memory so it's not a physical limit. I was able to get the firmware size just below 16kB with some optimizations like -mno-long-calls so it's not an urgent bug for me but it should be investigated and fixed.

verbose log is here (except it's missing the first part of the flashing, sorry):
http://pastebin.com/UEzrNTK2

**Comment by shumatech** [comment]
I do not have a SAM4S device to test this on.
