### ISSUE TITLE
What did you use to build this?

### ISSUE THREAD

**Issue by jkmiller11** [shumatech/BOSSA#3]
I have been been having a hard time building this from the source. Did you use mingw32?

**Comment by cmaglie** [comment]
@jkmiller11 
Since two years passed, I guess you solved it already...

BTW for future reference: yes, you need mingw32 and wxWidgets if you build the GUI. If you need only the commandline you can go straight with `make bin/bossac.exe` and the GUI part is skipped.

**Comment by NPellet** [comment]
That's really good to know when building on a RaspberryPI without GUI.
Should be written in bold in the docs :)
