### ISSUE TITLE
Pages to erase

### ISSUE THREAD

**Issue by resdevok** [shumatech/BOSSA#36]
Hi,
it could be very useful to have an additional parameter for the erase command: the total pages to erase. Indeed, it can be used to keep data stored in NVM with the EEPROM emulation driver.

**Comment by shumatech** [comment]
The EFC and EEFC flash controllers on all non-SAMD Atmel devices only supports a full chip erase or an auto-erase before writing so this cannot be done.  It might be possible on a SAMD though I don't know much about them.

**Comment by resdevok** [comment]
Hi shumatech,
thanks so much for your reply.
Yes on a SAMD is possible: in fact we modified ATSAMD21G18A_FLASH_PAGES from 4096 to 4032 to keep data stored at the and of the flash and it properly works.

**Comment by SietseAchterop** [comment]
The nRF52640 can erase on a page base, and it would indeed nice to be able to do partial erase!
