### ISSUE TITLE
OS X 10.10 build issues

### ISSUE THREAD

**Issue by dognotdog** [shumatech/BOSSA#37]
Getting errors below when compiling current master, after changing the Darwin build params to (because target issues up to at least OSX version 10.7):
```
COMMON_CXXFLAGS= -arch x86_64 -mmacosx-version-min=10.10 -std=gnu++11 -stdlib=libc++
COMMON_LDFLAGS= -arch x86_64 -mmacosx-version-min=10.10

```

The errors:
```
src/Command.cpp:719:23: error: comparison between pointer and integer ('char *' and 'int')
            if (input == '\0' ||
                ~~~~~ ^  ~~~~
src/Command.cpp:822:23: error: comparison between pointer and integer ('char *' and 'int')
            if (input == '\0' ||

```

Looks like a genuine bug where the pointer is compared to 0 instead of the data the pointer points to (as the pointer is rejected when NULL a line earlier anyway) changing to *input == ... apparently fixes things and it compiles and works

**Comment by shumatech** [comment]
Thanks for reporting!  This is now fixed.
