### ISSUE TITLE
Improvements in Bossa

### ISSUE THREAD

**Issue by TrukFraNoreg** [shumatech/BOSSA#42]
I have used bossa’s fork ( https://github.com/NorthboundNetworks/Bossa.git/trunk ) for a SAM4E16E CPU and I discovered some problems. My connection to the target was serial 115200baud. I have some suggestion for bossa. The same issues applies for http://www.shumatech.com/web/products/bossa ,

1.)	Increase in EefcFlash::waitFSR() usleep from 100 to 100000. Reason: erase would fail otherwise since it takes a long time. The same can be achieved by increasing tries to 500000.
An alternative would be the use of EWP (Erase page and write page). But it does not work for SAM4E, because EWP is just for a few pages ( More precisely: For the first 32 pages ).

2.)	In the same function (EefcFlash::waitFSR()) add 
        if (fsr0 & 0x2) 
            throw FlashCmdError();

3.)	Class EefcFlash could be improved if constructor reads properties of flash by using GETD. See details in http://www.atmel.com/Images/Atmel-11157-32-bit-Cortex-M4-Microcontroller-SAM4E16-SAM4E8_Datasheet.pdf  Chapter 20.4.3.1 Get Flash Descriptor Command.  Here some example code:
…
waitFSR();
writeFCR0(EEFC_FCMD_GETD, 0);
waitFSR();
uint32_t descriptor = readFRR0();
uint32_t sizeFlash = readFRR0():
uint32_t sizePage = readFRR0();
uint32_t numOfPlanes = readFRR0();
…

Since I have just one hardware (as mentioned above SAM4E16E) for testing I could not implement and commit the changes to your repositories.

**Comment by shumatech** [comment]
I believe 1 and 2 were addressed when I added support for the SAM4E family.  For 3., not everything needed to program the device is detectable so I would rather be explicit in the flash instantiation to isolate all device-specific flash knowledge to one place.
