### ISSUE TITLE
Read size not retrieved from text box

### ISSUE THREAD

**Issue by cw2** [shumatech/BOSSA#52]
It seems there is a bug in BossaWindow::OnRead(wxCommandEvent& event) [line 437](https://github.com/shumatech/BOSSA/blob/master/src/BossaWindow.cpp#L437):
```
        offset = strtol(_sizeTextCtrl->GetValue().mb_str(), &end, 0);
```
where the resulting number should be stored in `size` variable and not `offset`.

**Comment by shumatech** [comment]
Right you are.  Fix is in master.
