### ISSUE TITLE
File Dialog is not shown on GUI

### ISSUE THREAD

**Issue by rijesha** [shumatech/BOSSA#63]
I am using windows 10 and attempting to flash with the BOSSA GUI. I am unable to select a file. The file dialog box is collapsed and I can't find any way of selecting it or opening it.
I am installing with bossa-x64-1.8.msi

**Comment by rijesha** [comment]
The error I am always getting is "You must specify a file first"

**Comment by shumatech** [comment]
Try the 1.9.1 release.  It uses wxWidgets 1.9.1 which has some fixes for visual problems with high dpi displays.

**Comment by rijesha** [comment]
The new version has fixed this issue.
