### ISSUE TITLE
Bossa 1.8 x86 running on Win XP gives "......local hard drive" message

### ISSUE THREAD

**Issue by Riggar** [shumatech/BOSSA#64]
on installation message box shows "Installation directory must be on a local hard drive"

changing drive / names etc always gives the above message

running under cmd prompt admin with/
msiexec \i  path   with or without \q and any following parameter 

still gives the same message

**Comment by shumatech** [comment]
Sorry, but Bossa no longer supports Windows XP.  I only test and target Windows 7 and 10.

**Comment by Riggar** [comment]
ok thanks

Rigby

------ Original Message ------

**Comment by gvanem** [comment]
This is still an issue on Win-10:
![Bossa-install](https://github.com/shumatech/BOSSA/assets/945271/39c6136e-7219-40b1-8a76-d865d07f7d41)


OMG!
