### ISSUE TITLE
Running on Mac 10.13.3 hangs

### ISSUE THREAD

**Issue by deladriere** [shumatech/BOSSA#66]
I can compile without errors but running stops
Running bossa 1.9 shows

/Users/**/Downloads/BOSSA-master/bin/bossa ; exit;
17:41:35: Debug: Adding duplicate image handler for 'Windows bitmap file'
*** Caught unhandled unknown exception; terminating
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by deladriere** [comment]
I can compile without errors but running stops
Running bossa 1.9  shows 

 /Users/**/Downloads/BOSSA-master/bin/bossa ; exit;
17:41:35: Debug: Adding duplicate image handler for 'Windows bitmap file'
*** Caught unhandled unknown exception; terminating
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by deladriere** [comment]
It did run once but with error : could not find device ...

**Comment by shumatech** [comment]
I'm running 10.13.3 and bossa is running fine.  Perhaps it's your wxWidgets?  I'm using wxmac 3.0.3.1_1 from homebrew.  If this is still happening, reopen and post your wxWidgets version and build parameters.

**Comment by deladriere** [comment]
Ok works, thx
